[package]
name = "sarva-test"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ "lineserver" ]

[dependencies]
linegen = { path = "linegen" }

reqwest = { version = "0.12", features = ["blocking"] }
